COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Category		YES	nvarchar	50	100					
Category_Chinese		YES	nvarchar	50	100					
Category_ID		YES	nvarchar	2	4					
-------------------------------
