COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Employee ID		YES	int			10	10	0		
ID		NO	int			10	10	0		
Password		YES	nvarchar	255	510					
Privilege ID		YES	int			10	10	0		
UserID		YES	nvarchar	255	510					
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
FK_Employee Privileges_Privileges	FOREIGN KEY	
PK_Employee Privileges	PRIMARY KEY	
