COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
created_at		NO	datetime						3	
id		NO	int			10	10	0		
updated_at		NO	datetime						3	
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK__orders__3213E83F6B28414A	PRIMARY KEY	
