COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Note		YES	nvarchar	50	100					
Status_ID		NO	int			10	10	0		
StatusName		YES	nvarchar	50	100					
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_PO_Status	PRIMARY KEY	
