COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Amount		NO	money			19	10	4		
Date		NO	date						0	
ID		NO	int			10	10	0		
Notes		YES	varchar	250	250					
Product_ID		NO	varchar	15	15					
Quantity		NO	float			53	2			
Tax		YES	float			53	2			
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_POS_Sales	PRIMARY KEY	
