COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
BottomPrice	((0))	YES	float			53	2			
Grade		NO	nvarchar	20	40					
GroupName		NO	nvarchar	20	40					
OnSalePrice	((0))	YES	float			53	2			
RegPrice	((0))	YES	float			53	2			
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_PriceGroupPrice	PRIMARY KEY	
