COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
GroupName		YES	nvarchar	20	40					
ProdNum		NO	nvarchar	15	30					
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_PriceGroupProd	PRIMARY KEY	
