COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Barcode		NO	nvarchar	15	30					
Created_At	(getdate())	NO	datetime						3	
ID		NO	int			10	10	0		
Normalized_Barcode		NO	nvarchar	15	30					
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_scan_logs	PRIMARY KEY	
