COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Category_ID		YES	nvarchar	2	4					
Sub_Cat_Chinese		YES	nvarchar	50	100					
Sub_Category		YES	nvarchar	50	100					
Sub_CategoryID		YES	nvarchar	4	8					
-------------------------------
