COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
PO_ID		NO	nvarchar	255	510					
Product_ID		NO	nvarchar	15	30					
Supplier_ID		NO	int			10	10	0		
-------------------------------
