COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
ID		NO	int			10	10	0		
Product_ID		YES	nvarchar	255	510					
SalePrice		YES	money			19	10	4		
SaleQuantity		YES	int			10	10	0		
Sales_ID		YES	int			10	10	0		
SalesDate		YES	datetime						3	
Store_ID		YES	int			10	10	0		
-------------------------------
CONSTRAINT_NAME	CONSTRAINT_TYPE	
PK_tblPOS	PRIMARY KEY	
