COLUMN_NAME	COLUMN_DEFAULT	IS_NULLABLE	DATA_TYPE	CHARACTER_MAXIMUM_LENGTH	CHARACTER_OCTET_LENGTH	NUMERIC_PRECISION	NUMERIC_PRECISION_RADIX	NUMERIC_SCALE	DATETIME_PRECISION	
Inventory		YES	float			53	2			
LocationCode		NO	nvarchar	50	100					
ProductID		NO	nvarchar	50	100					
-------------------------------
